### ISSUE TITLE
Issue when Disabling mods that add new perks

### ISSUE THREAD

**Issue by Dangerdino30** [Nacu0021/ExpeditionEnhanced#1]
If I enable a mod that adds new perks, then enable said perks, If I were to disable the mod afterwards the perks are still enabled, but do nothing and show up as Question marks in game, there doesn't seem to be a way to disable them without re-enabling the mod and then turning them off. This seems like it would be more of a core issue in expedition enhanced, and not as much of a issue as implementation of the mod, though I could be wrong.

**Comment by Nacu0021** [comment]
Weird, I remember having this issue but I also remember fixing it...
Thanks, I'm planning a big update coming soon so I'll look into it!
